version: 2

run:
  timeout: 10m

linters:
  enable:
    # Default linters
    - "errcheck"    # Detect unchecked errors
    - "govet"       # Reports suspicious constructs
    - "ineffassign" # Detects unused variable assignments
    - "staticcheck" # go vet on steroids
    - "unused"      # Detect unused constants, variables, functions and types

    # Suggested additional linters
    - "gocyclo"   # Detect cyclomatic complexity
    - "goconst"   # Detect repeated values that can be made constants
    - "gocritic"  # Provides diagnostics that check for bugs, performance and style issues.
    - "gosec"     # Security linter
    - "importas"  # Enforces consistent import aliases.
    - "misspell"  # Fix spelling errors
    - "revive"    # General purpose linter
    - "unconvert" # Detect unnecessary type conversions
    - "unparam"   # Detect unused function parameters

    # Optional
    - "bodyclose"  # Check whether HTTP response bodies are closed
    - "err113"     # Enforce standard error handling practices
    - "depguard"   # Forbid certain package imports
    - "dupl"       # Detect duplicate code
    - "errchkjson" # some JSON-specific checks
    - "mnd"        # Detect magic numbers
    - "nakedret"   # Detect naked returns

  settings:
    gocyclo:
      min-complexity: 20

    gosec:
      excludes:
        #- "G301" # Poor file permissions used when creating a directory
        #- "G302" # Poor file permissions used with chmod
        #- "G306" # Poor file permissions used when writing to a new file

    depguard:
      rules:
        filevalidator:
          files:
            - "**/internal/**"
          allow:
            - github.com/isseis/go-safe-cmd-runner/internal/safefileio
            - $gostd

        main:
          files:
            - $all
            - "!$test"
            - "!**/internal/**"
          allow:
            - github.com/isseis/go-safe-cmd-runner/internal/filevalidator
            - $gostd

    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign

      ignored-numbers:
        - '0o640' # Default file permissions for files
        - '0o750' # Default file permissions for directories

  exclusions:
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
