repos:
-   repo: local
    hooks:
    -   id: go-test
        name: go test
        entry: go test -v ./...
        language: system
        types: [go]
        pass_filenames: false
        verbose: true

    -   id: go-tidy
        name: go tidy
        entry: go mod tidy
        language: golang
        types: [go]
        pass_filenames: false
        verbose: true
    -   id: golangci-lint
        name: golangci-lint
        entry: /home/issei/go/bin/golangci-lint run
        language: system
        types: [go]
        pass_filenames: false

    -   id: py test
        name: python test
        entry: python3 scripts/test_additional_security_checks.py
        language: system
        pass_filenames: false
        always_run: true

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: no-commit-to-branch
        args: [--branch, main]

-   repo: https://github.com/shutter-network/pre-commit-go-hooks
    rev: 53239641ec106cda9a7acf9150c98be8d5ffa1ec
    hooks:
    -   id: gofumpt
    -   id: gci
