# Automatic internal variables group execution test
# Tests that all commands in a group share the same %{__runner_datetime} value
version = "1.0"

[global]
timeout = 30
log_level = "debug"
skip_standard_paths = true

# Group with multiple commands - all should use same DATETIME
[[groups]]
name = "timestamped_operations"
description = "Multiple operations with consistent timestamp"
priority = 1

[[groups.commands]]
name = "step1_create"
description = "Create directory with timestamp"
cmd = "echo"
args = ["mkdir /tmp/backup/run-%{__runner_datetime}"]

[[groups.commands]]
name = "step2_backup"
description = "Create backup with same timestamp"
cmd = "echo"
args = ["tar czf /tmp/backup/run-%{__runner_datetime}/data.tar.gz /data"]

[[groups.commands]]
name = "step3_log"
description = "Log completion with same timestamp"
cmd = "echo"
args = ["echo Completed at %{__runner_datetime} >> /tmp/backup/run-%{__runner_datetime}/backup.log"]

[[groups.commands]]
name = "step4_verify"
description = "Verify all used same timestamp"
cmd = "echo"
args = ["ls -la /tmp/backup/run-%{__runner_datetime}/"]

# Second group to verify different execution context
[[groups]]
name = "pid_tracking"
description = "Track runner PID across commands"
priority = 2

[[groups.commands]]
name = "show_runner_info"
description = "Display runner information"
cmd = "echo"
args = ["Runner PID: %{__runner_pid}, DateTime: %{__runner_datetime}"]

[[groups.commands]]
name = "create_pid_file"
description = "Create PID tracking file"
cmd = "echo"
args = ["echo %{__runner_pid} > /tmp/runner-%{__runner_pid}.pid"]

[[groups.commands]]
name = "verify_pid_file"
description = "Verify PID file was created"
cmd = "echo"
args = ["cat /tmp/runner-%{__runner_pid}.pid"]
