# Comprehensive test configuration file for go-safe-cmd-runner
# This file covers all major configuration features and edge cases for thorough testing
version = "1.0"

[global]
timeout = 60
workdir = "/tmp/cmd-runner-comprehensive"
log_level = "debug"
skip_standard_paths = true
# Global environment variables - comprehensive list for testing
env_allowlist = [
    "PATH",
    "HOME",
    "USER",
    "LANG",
    "LC_ALL",
    "SHELL",
    "TEST_GLOBAL_VAR",
    "COMPREHENSIVE_TEST",
    "NODE_ENV",
    "DEBUG_MODE",
    "GOTRACEBACK",
]
verify_files = ["/etc/passwd", "/bin/sh"]

# Group 1: Basic functionality test - no dependencies
[[groups]]
name = "basic_tests"
description = "Basic command execution tests without special features"
priority = 1

[[groups.commands]]
name = "simple_echo"
description = "Simple echo command test"
cmd = "echo"
args = ["Basic test successful"]

[[groups.commands]]
name = "environment_display"
description = "Display environment variables"
cmd = "env"
args = []

# Group 2: Security and privilege tests
[[groups]]
name = "security_tests"
description = "Security feature testing including privilege escalation"
priority = 2
# Group-level explicit environment allowlist (overrides global)
env_allowlist = ["PATH", "HOME", "TEST_SECURITY_VAR"]

[[groups.commands]]
name = "privileged_whoami"
description = "Test privileged command execution"
cmd = "/usr/bin/whoami"
args = []
privileged = true

[[groups.commands]]
name = "unprivileged_id"
description = "Test unprivileged command execution"
cmd = "id"
args = []
privileged = false

[[groups.commands]]
name = "custom_env_test"
description = "Test custom environment variables"
cmd = "printenv"
args = ["TEST_SECURITY_VAR"]
env = ["TEST_SECURITY_VAR=security_value"]

# Group 3: Resource management tests - temporary directories and cleanup
# TODO: Broken
[[groups]]
name = "resource_tests"
description = "Test temporary directory creation and cleanup"
priority = 3
temp_dir = true
cleanup = true

[[groups.commands]]
name = "create_temp_file"
description = "Create temporary file in temp directory"
cmd = "touch"
args = ["test_temp_file.txt"]

[[groups.commands]]
name = "list_temp_contents"
description = "List contents of temporary directory"
cmd = "ls"
args = ["-la"]

[[groups.commands]]
name = "write_temp_data"
description = "Write data to temporary file"
cmd = "echo"
args = ["Temporary data for testing"]

# Group 4: Working directory tests
[[groups]]
name = "workdir_tests"
description = "Test custom working directory functionality"
priority = 4
workdir = "/tmp/custom-workdir-test"

[[groups.commands]]
name = "test_workdir"
description = "Test working in custom directory"
cmd = "pwd"
args = []

[[groups.commands]]
name = "create_workdir_file"
description = "Create file in custom working directory"
cmd = "touch"
args = ["workdir_test_file.txt"]

# Group 5: Environment variable inheritance tests
[[groups]]
name = "env_inheritance_tests"
description = "Test environment variable inheritance modes"
priority = 5
# Test inheritance mode - inherits from global by not specifying env_allowlist

[[groups.commands]]
name = "test_global_inheritance"
description = "Test global environment variable inheritance"
cmd = "printenv"
args = ["TEST_GLOBAL_VAR"]
env = ["TEST_GLOBAL_VAR=inherited_value"]

[[groups.commands]]
name = "test_node_env"
description = "Test NODE_ENV from global allowlist"
cmd = "printenv"
args = ["NODE_ENV"]
env = ["NODE_ENV=test_environment"]

# Group 6: Environment variable rejection tests
[[groups]]
name = "env_rejection_tests"
description = "Test environment variable rejection"
priority = 6
# Explicit empty allowlist - rejects all environment variables
env_allowlist = []

[[groups.commands]]
name = "test_env_rejection"
description = "Test that environment variables are rejected"
cmd = "echo"
args = ["Should not see any custom env vars"]

# Group 7: Timeout tests
[[groups]]
name = "timeout_tests"
description = "Test timeout functionality at command and global level"
priority = 7

[[groups.commands]]
name = "quick_command"
description = "Quick command that should complete within timeout"
cmd = "echo"
args = ["Quick completion"]
timeout = 5

[[groups.commands]]
name = "medium_command"
description = "Medium duration command"
cmd = "sleep"
args = ["2"]
timeout = 10

# Group 8: File verification tests
[[groups]]
name = "file_verification_tests"
description = "Test file verification functionality"
priority = 8
verify_files = ["/bin/echo", "/usr/bin/env"]

[[groups.commands]]
name = "verify_system_files"
description = "Test system file verification"
cmd = "echo"
args = ["File verification test"]

[[groups.commands]]
name = "test_verified_command"
description = "Use verified command"
cmd = "/bin/echo"
args = ["Using verified command"]

# Group 9: Complex dependency chain test
[[groups]]
name = "dependency_chain_a"
description = "First link in dependency chain"
priority = 9

[[groups.commands]]
name = "chain_step_a"
description = "First step in dependency chain"
cmd = "echo"
args = ["Dependency chain step A"]

[[groups]]
name = "dependency_chain_b"
description = "Second link in dependency chain"
priority = 10

[[groups.commands]]
name = "chain_step_b"
description = "Second step in dependency chain"
cmd = "echo"
args = ["Dependency chain step B"]

[[groups]]
name = "dependency_chain_c"
description = "Final link in dependency chain"
priority = 11

[[groups.commands]]
name = "chain_step_c"
description = "Final step in dependency chain"
cmd = "echo"
args = ["Dependency chain step C - complete"]

# Group 10: Multiple dependencies test
[[groups]]
name = "multi_dependency_test"
description = "Test group with multiple dependencies"
priority = 12

[[groups.commands]]
name = "multi_dep_summary"
description = "Summarize multi-dependency test"
cmd = "echo"
args = ["Multi-dependency test completed successfully"]

# Group 11: All features combined
[[groups]]
name = "comprehensive_final"
description = "Final comprehensive test combining all features"
priority = 13
temp_dir = true
cleanup = true
workdir = "/tmp/final-comprehensive-test"
env_allowlist = ["PATH", "HOME", "FINAL_TEST_VAR"]
verify_files = ["/bin/echo"]

[[groups.commands]]
name = "final_privileged_test"
description = "Final privileged operation test"
cmd = "/usr/bin/whoami"
args = []
privileged = true
timeout = 30

[[groups.commands]]
name = "final_env_test"
description = "Final environment variable test"
cmd = "printenv"
args = ["FINAL_TEST_VAR"]
env = ["FINAL_TEST_VAR=comprehensive_success"]

[[groups.commands]]
name = "final_summary"
description = "Final comprehensive test summary"
cmd = "echo"
args = ["🎉 All comprehensive tests completed successfully!"]
timeout = 15
