# Global and Group Environment Variables - Basic Example
#
# This sample demonstrates the basic usage of global.env and groups[].env fields.
# It shows how to define environment variables at different levels and how they
# are inherited and overridden.

version = "1.0"

[global]
# Global environment variables: available to all groups and commands
env = [
    "BASE_DIR=/opt/myapp",
    "LOG_LEVEL=info",
    "CONFIG_FILE=/etc/myapp/config.yaml",
]

# Allow system environment variables
env_allowlist = ["HOME", "PATH", "USER"]

# Verify critical files before execution
verify_files = ["${BASE_DIR}/verify.sh"]

# Skip standard path validation for system commands
skip_standard_paths = true

# Database group: demonstrates group-level environment variables
[[groups]]
name = "database"
description = "Database management tasks"

# Group-level environment variables: available to all commands in this group
env = [
    "DB_HOST=localhost",
    "DB_PORT=5432",
    "DB_NAME=myapp_db",
    "DB_DATA=${BASE_DIR}/db-data",  # References global.env variable
]

[[groups.commands]]
name = "show_db_config"
description = "Display database configuration"
cmd = "/bin/echo"
args = [
    "Database: ${DB_NAME} at ${DB_HOST}:${DB_PORT}",
    "Data directory: ${DB_DATA}",
]

[[groups.commands]]
name = "show_log_level"
description = "Display log level from global.env"
cmd = "/bin/echo"
args = ["Log level: ${LOG_LEVEL}"]  # References global.env variable

# Web server group: demonstrates variable override
[[groups]]
name = "web"
description = "Web server management tasks"

# Override global.env LOG_LEVEL for this group
env = [
    "LOG_LEVEL=debug",              # Overrides global.env
    "WEB_DIR=${BASE_DIR}/web",      # References global.env
    "PORT=8080",                    # Group-specific variable
]

[[groups.commands]]
name = "show_web_config"
description = "Display web server configuration"
cmd = "/bin/echo"
args = [
    "Web directory: ${WEB_DIR}",
    "Port: ${PORT}",
    "Log level: ${LOG_LEVEL}",  # Will show "debug" (overridden)
]

# System tools group: demonstrates system env variable expansion
[[groups]]
name = "tools"
description = "System utility tasks"

# Extend system PATH variable
env = [
    "PATH=/opt/custom/bin:${PATH}",  # Extends system PATH
    "TOOL_DIR=${HOME}/tools",        # References system HOME variable
]

[[groups.commands]]
name = "show_path"
description = "Display extended PATH"
cmd = "/bin/echo"
args = ["Custom PATH: ${PATH}"]

[[groups.commands]]
name = "show_tool_dir"
description = "Display tool directory"
cmd = "/bin/echo"
args = ["Tool directory: ${TOOL_DIR}"]
