version = "1.0"

[global]
workdir = "/tmp/cmd-runner"
log_level = "debug"
skip_standard_paths = true
# Environment variable allowlist for testing
env_allowlist = [
    "PATH",
    "HOME",
    "USER",
    "LANG",
    "NODE_ENV",
    "DEBUG",
    "CUSTOM_VAR",
]

[[groups]]
name = "test"
description = "Test group for command execution with temporary directory"
priority = 1
depends_on = []
temp_dir = true                                                           # Create temporary directory for testing
cleanup = true                                                            # Auto-cleanup after test execution

[[groups.commands]]
name = "show_environment"
description = "Display environment information"
cmd = "echo"
args = ["Environment: development, App: myapp-dev, Port: 3000"]
env = ["NODE_ENV=development", "DEBUG=true", "CUSTOM_VAR=${LANG}"]

[[groups.commands]]
name = "show_environment_variables"
description = "Display environment information"
cmd = "env"
args = []

[[groups.commands]]
name = "print_effective_user"
description = "Display effective user"
privileged = true
cmd = "whoami"
args = []
