#!/usr/bin/env python3
"""Generate Go syscall number tables from Linux kernel header files.

Usage:
    python3 scripts/generate_syscall_table.py [--x86-header PATH] [--arm64-header PATH]
                                               [--macos-header PATH]

Options:
    --x86-header PATH    Path to x86_64 syscall header
                         (default: /usr/include/x86_64-linux-gnu/asm/unistd_64.h)
    --arm64-header PATH  Path to arm64/generic syscall header
                         (default: /usr/include/asm-generic/unistd.h)
    --macos-header PATH  Path to macOS BSD syscall header
                         (e.g. $(xcrun --show-sdk-path)/usr/include/sys/syscall.h)

Writes:
    internal/runner/security/elfanalyzer/x86_syscall_numbers.go
    internal/runner/security/elfanalyzer/arm64_syscall_numbers.go
    internal/libccache/macos_syscall_numbers.go  (only when --macos-header is given)
"""

import argparse
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Network syscall names (architecture-independent names).
# These are the syscalls that indicate network capability.
# Matches the requirements (FR-3.1.5).
# ---------------------------------------------------------------------------
NETWORK_SYSCALL_NAMES = {
    "socket",
    "connect",
    "accept",
    "accept4",
    "sendto",
    "recvfrom",
    "sendmsg",
    "recvmsg",
    "bind",
    "listen",
    "socketpair",
    "recvmmsg",
    "sendmmsg",
}

# macOS-specific network syscall names.
# accept4 / recvmmsg / sendmmsg are Linux-specific and absent on macOS.
# shutdown / setsockopt / getsockopt / getpeername / getsockname are included
# to match the existing networkSyscallWrapperNames in macos_syscall_table.go.
MACOS_NETWORK_SYSCALL_NAMES = {
    "socket",
    "connect",
    "accept",
    "sendto",
    "recvfrom",
    "sendmsg",
    "recvmsg",
    "bind",
    "listen",
    "socketpair",
    "shutdown",
    "setsockopt",
    "getsockopt",
    "getpeername",
    "getsockname",
}

MACOS_NETWORK_SYSCALL_SUFFIXES = (
    "_nocancel",
)


# Meta/size constants that appear in kernel headers as __NR_<name> but are
# not actual syscall numbers.  __NR_syscalls, for example, is the total count
# of syscalls (last_syscall + 1), not a callable syscall entry point.
_META_NAMES: frozenset[str] = frozenset({"syscalls"})

# Meta/size constants that appear in macOS syscall headers as SYS_<name> but are
# not callable syscall entry points.  SYS_MAXSYSCALL is the total count.
_MACOS_META_NAMES: frozenset[str] = frozenset({"MAXSYSCALL"})


def parse_header(path: str) -> dict[str, int]:
    """Parse ``#define __NR_<name> <number>`` lines from a C header file.

    Returns a dict mapping syscall name to number.
    Lines with non-integer values (e.g. ``(__NR_Linux + N)``) are skipped.
    Meta/size constants listed in ``_META_NAMES`` are excluded.
    """
    pattern = re.compile(r"^#define\s+__NR_(\w+)\s+(\d+)\s*$")
    result: dict[str, int] = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            m = pattern.match(line)
            if m:
                name, number = m.group(1), int(m.group(2))
                if name in _META_NAMES:
                    continue
                result[name] = number
    return result


def parse_macos_header(path: str) -> dict[str, int]:
    """Parse ``#define SYS_<name> <number>`` lines from a macOS syscall header.

    Returns a dict mapping syscall name to number.
    Lines with trailing comments (e.g. ``/* read(2) */``) are accepted.
    Meta/size constants listed in ``_MACOS_META_NAMES`` are excluded.
    """
    pattern = re.compile(r"^#define\s+SYS_(\w+)\s+(\d+).*$")
    result: dict[str, int] = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            m = pattern.match(line)
            if m:
                name, number = m.group(1), int(m.group(2))
                if name in _MACOS_META_NAMES:
                    continue
                result[name] = number
    return result


def is_macos_network_syscall(name: str) -> bool:
    """Return whether the macOS syscall name should be classified as network-related."""
    if name in MACOS_NETWORK_SYSCALL_NAMES:
        return True
    for suffix in MACOS_NETWORK_SYSCALL_SUFFIXES:
        if name.endswith(suffix) and name[: -len(suffix)] in MACOS_NETWORK_SYSCALL_NAMES:
            return True
    return False


# ---------------------------------------------------------------------------
# Go source template
# ---------------------------------------------------------------------------

FILE_HEADER = """\
// Code generated by scripts/generate_syscall_table.py; DO NOT EDIT.
// Source: {source}
// Regenerate: make generate-syscall-tables

//nolint:dupl // table structure and methods are structurally identical across architectures
package elfanalyzer
"""

MACOS_FILE_HEADER = """\
// Code generated by scripts/generate_syscall_table.py; DO NOT EDIT.
// Source: {source}
// Regenerate: make generate-syscall-tables

package libccache
"""

STRUCT_TEMPLATE = """\
// {struct_name} implements SyscallNumberTable for {arch_desc}.
type {struct_name} struct {{
\tsyscalls       map[int]SyscallDefinition
\tnetworkNumbers []int
}}

// {constructor_name} creates a new syscall table for {arch_desc}.{constructor_extra_comment}
func {constructor_name}() *{struct_name} {{
\ttable := &{struct_name}{{
\t\tsyscalls: make(map[int]SyscallDefinition),
\t}}
{{body}}
\treturn table
}}

// GetSyscallName returns the syscall name for the given number.
func (t *{struct_name}) GetSyscallName(number int) string {{
\tif def, ok := t.syscalls[number]; ok {{
\t\treturn def.Name
\t}}
\treturn ""
}}

// IsNetworkSyscall returns true if the syscall is network-related.
func (t *{struct_name}) IsNetworkSyscall(number int) bool {{
\tif def, ok := t.syscalls[number]; ok {{
\t\treturn def.IsNetwork
\t}}
\treturn false
}}

// GetNetworkSyscalls returns all network-related syscall numbers.
// Returns a copy to prevent callers from mutating the internal state.
func (t *{struct_name}) GetNetworkSyscalls() []int {{
\tresult := make([]int, len(t.networkNumbers))
\tcopy(result, t.networkNumbers)
\treturn result
}}
"""


def make_struct_template(struct_name: str, arch_desc: str, constructor_name: str, constructor_extra_comment: str = "") -> str:
    """Instantiate STRUCT_TEMPLATE for a given architecture.

    Returns a string with all architecture-specific names filled in and Go
    braces rendered as literal ``{``/``}``.  The token ``{body}`` is left as-is
    so that ``generate()`` can splice in the constructor body with a plain
    ``str.replace("{body}", body)``.
    """
    if constructor_extra_comment:
        constructor_extra_comment = "\n// " + constructor_extra_comment

    # STRUCT_TEMPLATE uses {{/}} to escape Go braces for Python str.format(),
    # and {name} for the named placeholders.  Call .format() to substitute the
    # architecture parameters; str.format() automatically unescapes {{/}} to
    # {/} in the output, giving us literal Go braces.  Pass body="{body}" so
    # that placeholder survives for the later str.replace() in generate().
    return STRUCT_TEMPLATE.format(
        struct_name=struct_name,
        arch_desc=arch_desc,
        constructor_name=constructor_name,
        constructor_extra_comment=constructor_extra_comment,
        body="{body}",
    )


def build_body(syscalls: dict[str, int]) -> str:
    """Build the constructor body listing all syscalls."""
    lines = []

    lines.append("\tsyscalls := []SyscallDefinition{")
    processed_numbers: set[int] = set()
    # Sort by number, then by name length to prefer shorter names for a given number,
    # and finally by name alphabetically for deterministic output.
    sorted_syscalls = sorted(
        syscalls.items(), key=lambda x: (x[1], len(x[0]), x[0]))
    for name, num in sorted_syscalls:
        if num in processed_numbers:
            continue
        processed_numbers.add(num)
        is_network = "true" if name in NETWORK_SYSCALL_NAMES else "false"
        lines.append(f'\t\t{{{num}, "{name}", {is_network}}},')
    lines.append("\t}")
    lines.append("\tfor _, def := range syscalls {")
    lines.append("\t\ttable.syscalls[def.Number] = def")
    lines.append("\t\tif def.IsNetwork {")
    lines.append(
        "\t\t\ttable.networkNumbers = append(table.networkNumbers, def.Number)")
    lines.append("\t\t}")
    lines.append("\t}")

    return "\n".join(lines) + "\n"


def generate(source: str, struct_template: str, output: str) -> None:
    syscalls = parse_header(source)
    if not syscalls:
        print(f"ERROR: no syscalls parsed from {source}", file=sys.stderr)
        sys.exit(1)

    body = build_body(syscalls)
    # Use only the basename so the comment is stable regardless of where on
    # disk the caller installed the kernel headers.
    source_label = Path(source).name
    # struct_template contains Go braces that would confuse str.format(), so
    # substitute the {body} sentinel with a plain str.replace() instead.
    content = (
        FILE_HEADER.format(source=source_label)
        + "\n"
        + struct_template.replace("{body}", body)
    )

    Path(output).write_text(content, encoding="utf-8")
    print(f"Generated {output}  ({len(syscalls)} syscalls from {source})")


def generate_macos(source: str, output: str) -> None:
    """Generate macOS BSD syscall table for the libccache package.

    The output file defines ``macOSSyscallEntries`` using ``macOSSyscallEntry``
    (defined in macos_syscall_table.go) and is committed to the repository so
    that builds on non-macOS hosts (e.g. Linux CI) continue to work without
    needing macOS SDK headers.
    """
    syscalls = parse_macos_header(source)
    if not syscalls:
        print(f"ERROR: no syscalls parsed from {source}", file=sys.stderr)
        sys.exit(1)

    source_label = Path(source).name
    lines: list[str] = []
    lines.append(MACOS_FILE_HEADER.format(source=source_label))
    lines.append(
        "// macOSSyscallEntries defines the macOS arm64 BSD syscall table.")
    lines.append(
        "// Keys are syscall numbers without the BSD class prefix 0x2000000.")
    lines.append("var macOSSyscallEntries = map[int]macOSSyscallEntry{")

    processed_numbers: set[int] = set()
    # Sort by number, then by name length to prefer shorter names for a given number,
    # and finally by name alphabetically for deterministic output.
    sorted_syscalls = sorted(
        syscalls.items(), key=lambda x: (x[1], len(x[0]), x[0]))
    for name, number in sorted_syscalls:
        if number in processed_numbers:
            continue
        processed_numbers.add(number)
        is_network = "true" if is_macos_network_syscall(name) else "false"
        lines.append(
            f'\t{number}:\t{{name: "{name}", isNetwork: {is_network}}},')

    lines.append("}")
    lines.append("")

    content = "\n".join(lines)
    Path(output).write_text(content, encoding="utf-8")
    print(f"Generated {output}  ({len(processed_numbers)} syscalls from {source})")


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--x86-header",
        default=None,
        help="Path to x86_64 syscall header (default: /usr/include/x86_64-linux-gnu/asm/unistd_64.h)",
    )
    parser.add_argument(
        "--arm64-header",
        default=None,
        help="Path to arm64/generic syscall header (default: /usr/include/asm-generic/unistd.h)",
    )
    parser.add_argument(
        "--macos-header",
        default=None,
        help="Path to macOS BSD syscall header (e.g. $(xcrun --show-sdk-path)/usr/include/sys/syscall.h)",
    )
    args = parser.parse_args()

    if args.x86_header is None and args.arm64_header is None and args.macos_header is None:
        # Default: generate all Linux tables using well-known paths.
        args.x86_header = "/usr/include/x86_64-linux-gnu/asm/unistd_64.h"
        args.arm64_header = "/usr/include/asm-generic/unistd.h"

    repo_root = Path(__file__).parent.parent
    out_dir = repo_root / "internal/runner/security/elfanalyzer"

    if args.x86_header is not None:
        generate(
            source=args.x86_header,
            struct_template=make_struct_template(
                struct_name="X86_64SyscallTable",
                arch_desc="x86_64 Linux",
                constructor_name="NewX86_64SyscallTable",
            ),
            output=str(out_dir / "x86_syscall_numbers.go"),
        )
    if args.arm64_header is not None:
        generate(
            source=args.arm64_header,
            struct_template=make_struct_template(
                struct_name="ARM64LinuxSyscallTable",
                arch_desc="arm64 Linux",
                constructor_name="NewARM64LinuxSyscallTable",
                constructor_extra_comment="Syscall numbers are from the ARM64 Linux ABI (include/uapi/asm-generic/unistd.h).",
            ),
            output=str(out_dir / "arm64_syscall_numbers.go"),
        )

    if args.macos_header is not None:
        macos_out_dir = repo_root / "internal/libccache"
        generate_macos(
            source=args.macos_header,
            output=str(macos_out_dir / "macos_syscall_numbers.go"),
        )


if __name__ == "__main__":
    main()
