#!/usr/bin/env python3
"""Generate Go syscall number tables from Linux kernel header files.

Usage:
    python3 scripts/generate_syscall_table.py

Reads:
    /usr/include/x86_64-linux-gnu/asm/unistd_64.h  (x86_64)
    /usr/include/asm-generic/unistd.h               (arm64 / generic)

Writes:
    internal/runner/security/elfanalyzer/x86_syscall_numbers.go
    internal/runner/security/elfanalyzer/arm64_syscall_numbers.go
"""

import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Network syscall names (architecture-independent names).
# These are the syscalls that indicate network capability.
# Matches the requirements (FR-3.1.5).
# ---------------------------------------------------------------------------
NETWORK_SYSCALL_NAMES = {
    "socket",
    "connect",
    "accept",
    "accept4",
    "sendto",
    "recvfrom",
    "sendmsg",
    "recvmsg",
    "bind",
    "listen",
    "socketpair",
    "recvmmsg",
    "sendmmsg",
}


def parse_header(path: str) -> dict[str, int]:
    """Parse ``#define __NR_<name> <number>`` lines from a C header file.

    Returns a dict mapping syscall name to number.
    Lines with non-integer values (e.g. ``(__NR_Linux + N)``) are skipped.
    """
    pattern = re.compile(r"^#define\s+__NR_(\w+)\s+(\d+)\s*$")
    result: dict[str, int] = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            m = pattern.match(line)
            if m:
                name, number = m.group(1), int(m.group(2))
                result[name] = number
    return result


# ---------------------------------------------------------------------------
# Go source template
# ---------------------------------------------------------------------------

FILE_HEADER = """\
// Code generated by scripts/generate_syscall_table.py; DO NOT EDIT.
// Source: {source}
// Regenerate: make generate-syscall-tables

//nolint:dupl // table structure and methods are structurally identical across architectures
package elfanalyzer
"""

STRUCT_X86 = """\
// X86_64SyscallTable implements SyscallNumberTable for x86_64 Linux.
type X86_64SyscallTable struct {{
\tsyscalls       map[int]SyscallDefinition
\tnetworkNumbers []int
}}

// NewX86_64SyscallTable creates a new syscall table for x86_64 Linux.
func NewX86_64SyscallTable() *X86_64SyscallTable {{
\ttable := &X86_64SyscallTable{{
\t\tsyscalls: make(map[int]SyscallDefinition),
\t}}
{body}
\treturn table
}}

// GetSyscallName returns the syscall name for the given number.
func (t *X86_64SyscallTable) GetSyscallName(number int) string {{
\tif def, ok := t.syscalls[number]; ok {{
\t\treturn def.Name
\t}}
\treturn ""
}}

// IsNetworkSyscall returns true if the syscall is network-related.
func (t *X86_64SyscallTable) IsNetworkSyscall(number int) bool {{
\tif def, ok := t.syscalls[number]; ok {{
\t\treturn def.IsNetwork
\t}}
\treturn false
}}

// GetNetworkSyscalls returns all network-related syscall numbers.
// Returns a copy to prevent callers from mutating the internal state.
func (t *X86_64SyscallTable) GetNetworkSyscalls() []int {{
\tresult := make([]int, len(t.networkNumbers))
\tcopy(result, t.networkNumbers)
\treturn result
}}
"""

STRUCT_ARM64 = """\
// ARM64LinuxSyscallTable implements SyscallNumberTable for arm64 Linux.
type ARM64LinuxSyscallTable struct {{
\tsyscalls       map[int]SyscallDefinition
\tnetworkNumbers []int
}}

// NewARM64LinuxSyscallTable creates a new syscall table for arm64 Linux.
// Syscall numbers are from the ARM64 Linux ABI (include/uapi/asm-generic/unistd.h).
func NewARM64LinuxSyscallTable() *ARM64LinuxSyscallTable {{
\ttable := &ARM64LinuxSyscallTable{{
\t\tsyscalls: make(map[int]SyscallDefinition),
\t}}
{body}
\treturn table
}}

// GetSyscallName returns the syscall name for the given number.
func (t *ARM64LinuxSyscallTable) GetSyscallName(number int) string {{
\tif def, ok := t.syscalls[number]; ok {{
\t\treturn def.Name
\t}}
\treturn ""
}}

// IsNetworkSyscall returns true if the syscall is network-related.
func (t *ARM64LinuxSyscallTable) IsNetworkSyscall(number int) bool {{
\tif def, ok := t.syscalls[number]; ok {{
\t\treturn def.IsNetwork
\t}}
\treturn false
}}

// GetNetworkSyscalls returns all network-related syscall numbers.
// Returns a copy to prevent callers from mutating the internal state.
func (t *ARM64LinuxSyscallTable) GetNetworkSyscalls() []int {{
\tresult := make([]int, len(t.networkNumbers))
\tcopy(result, t.networkNumbers)
\treturn result
}}
"""


def build_body(syscalls: dict[str, int]) -> str:
    """Build the constructor body listing all syscalls."""
    network = {name: num for name, num in syscalls.items() if name in NETWORK_SYSCALL_NAMES}
    non_network = {name: num for name, num in syscalls.items() if name not in NETWORK_SYSCALL_NAMES}

    lines = []

    lines.append("\t// Network-related syscalls")
    lines.append("\tnetworkSyscalls := []SyscallDefinition{")
    for name, num in sorted(network.items(), key=lambda x: x[1]):
        lines.append(f'\t\t{{{num}, "{name}", true}},')
    lines.append("\t}")
    lines.append("\tfor _, def := range networkSyscalls {")
    lines.append("\t\ttable.syscalls[def.Number] = def")
    lines.append("\t\ttable.networkNumbers = append(table.networkNumbers, def.Number)")
    lines.append("\t}")
    lines.append("")
    lines.append("\t// Non-network syscalls")
    lines.append("\tnonNetworkSyscalls := []SyscallDefinition{")
    for name, num in sorted(non_network.items(), key=lambda x: x[1]):
        lines.append(f'\t\t{{{num}, "{name}", false}},')
    lines.append("\t}")
    lines.append("\tfor _, def := range nonNetworkSyscalls {")
    lines.append("\t\ttable.syscalls[def.Number] = def")
    lines.append("\t}")

    return "\n".join(lines) + "\n"


def generate(source: str, struct_template: str, output: str) -> None:
    syscalls = parse_header(source)
    if not syscalls:
        print(f"ERROR: no syscalls parsed from {source}", file=sys.stderr)
        sys.exit(1)

    body = build_body(syscalls)
    content = (
        FILE_HEADER.format(source=source)
        + "\n"
        + struct_template.format(body=body)
    )

    Path(output).write_text(content, encoding="utf-8")
    print(f"Generated {output}  ({len(syscalls)} syscalls from {source})")


def main() -> None:
    repo_root = Path(__file__).parent.parent
    out_dir = repo_root / "internal/runner/security/elfanalyzer"

    generate(
        source="/usr/include/x86_64-linux-gnu/asm/unistd_64.h",
        struct_template=STRUCT_X86,
        output=str(out_dir / "x86_syscall_numbers.go"),
    )
    generate(
        source="/usr/include/asm-generic/unistd.h",
        struct_template=STRUCT_ARM64,
        output=str(out_dir / "arm64_syscall_numbers.go"),
    )


if __name__ == "__main__":
    main()
