#!/usr/bin/env python3
"""Generate Go syscall number tables from Linux kernel header files.

Usage:
    python3 scripts/generate_syscall_table.py [--x86-header PATH] [--arm64-header PATH]

Options:
    --x86-header PATH    Path to x86_64 syscall header
                         (default: /usr/include/x86_64-linux-gnu/asm/unistd_64.h)
    --arm64-header PATH  Path to arm64/generic syscall header
                         (default: /usr/include/asm-generic/unistd.h)

Writes:
    internal/runner/security/elfanalyzer/x86_syscall_numbers.go
    internal/runner/security/elfanalyzer/arm64_syscall_numbers.go
"""

import argparse
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Network syscall names (architecture-independent names).
# These are the syscalls that indicate network capability.
# Matches the requirements (FR-3.1.5).
# ---------------------------------------------------------------------------
NETWORK_SYSCALL_NAMES = {
    "socket",
    "connect",
    "accept",
    "accept4",
    "sendto",
    "recvfrom",
    "sendmsg",
    "recvmsg",
    "bind",
    "listen",
    "socketpair",
    "recvmmsg",
    "sendmmsg",
}


def parse_header(path: str) -> dict[str, int]:
    """Parse ``#define __NR_<name> <number>`` lines from a C header file.

    Returns a dict mapping syscall name to number.
    Lines with non-integer values (e.g. ``(__NR_Linux + N)``) are skipped.
    """
    pattern = re.compile(r"^#define\s+__NR_(\w+)\s+(\d+)\s*$")
    result: dict[str, int] = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            m = pattern.match(line)
            if m:
                name, number = m.group(1), int(m.group(2))
                result[name] = number
    return result


# ---------------------------------------------------------------------------
# Go source template
# ---------------------------------------------------------------------------

FILE_HEADER = """\
// Code generated by scripts/generate_syscall_table.py; DO NOT EDIT.
// Source: {source}
// Regenerate: make generate-syscall-tables

//nolint:dupl // table structure and methods are structurally identical across architectures
package elfanalyzer
"""

STRUCT_TEMPLATE = """\
// {struct_name} implements SyscallNumberTable for {arch_desc}.
type {struct_name} struct {{
\tsyscalls       map[int]SyscallDefinition
\tnetworkNumbers []int
}}

// {constructor_name} creates a new syscall table for {arch_desc}.{constructor_extra_comment}
func {constructor_name}() *{struct_name} {{
\ttable := &{struct_name}{{
\t\tsyscalls: make(map[int]SyscallDefinition),
\t}}
{{body}}
\treturn table
}}

// GetSyscallName returns the syscall name for the given number.
func (t *{struct_name}) GetSyscallName(number int) string {{
\tif def, ok := t.syscalls[number]; ok {{
\t\treturn def.Name
\t}}
\treturn ""
}}

// IsNetworkSyscall returns true if the syscall is network-related.
func (t *{struct_name}) IsNetworkSyscall(number int) bool {{
\tif def, ok := t.syscalls[number]; ok {{
\t\treturn def.IsNetwork
\t}}
\treturn false
}}

// GetNetworkSyscalls returns all network-related syscall numbers.
// Returns a copy to prevent callers from mutating the internal state.
func (t *{struct_name}) GetNetworkSyscalls() []int {{
\tresult := make([]int, len(t.networkNumbers))
\tcopy(result, t.networkNumbers)
\treturn result
}}
"""


def make_struct_template(struct_name: str, arch_desc: str, constructor_name: str, constructor_extra_comment: str = "") -> str:
    """Instantiate STRUCT_TEMPLATE for a given architecture, returning a body-parameterized template string.

    The returned string still contains a single ``{body}`` placeholder so that
    ``generate()`` can fill in the constructor body via ``.format(body=...)``.
    """
    if constructor_extra_comment:
        constructor_extra_comment = "\n// " + constructor_extra_comment

    # STRUCT_TEMPLATE uses {{...}} to escape Go braces and {name} for Python
    # format fields.  We want to produce a string that still has one {body}
    # placeholder (for the second .format() call in generate()) but has all
    # Go braces escaped.  Strategy:
    #   1. Escape every brace in the template so .format() sees none.
    #   2. Un-escape only the known named fields we want to substitute.
    #   3. Call .format() to fill in the architecture parameters.
    #   4. The {body} placeholder survives because we un-escaped it explicitly.

    # Step 1: escape all braces (turns {{ -> {{{{ and {name} -> {{name}})
    escaped_template = STRUCT_TEMPLATE.replace("{", "{{").replace("}", "}}")

    # Step 2: un-escape the named format fields we want to substitute now.
    for field in ("struct_name", "arch_desc", "constructor_name", "constructor_extra_comment", "body"):
        escaped_template = escaped_template.replace("{{" + field + "}}", "{" + field + "}")

    filled = escaped_template.format(
        struct_name=struct_name,
        arch_desc=arch_desc,
        constructor_name=constructor_name,
        constructor_extra_comment=constructor_extra_comment,
        body="{body}",  # pass through as literal placeholder for generate()
    )
    return filled


def build_body(syscalls: dict[str, int]) -> str:
    """Build the constructor body listing all syscalls."""
    lines = []

    lines.append("\tsyscalls := []SyscallDefinition{")
    for name, num in sorted(syscalls.items(), key=lambda x: x[1]):
        is_network = "true" if name in NETWORK_SYSCALL_NAMES else "false"
        lines.append(f'\t\t{{{num}, "{name}", {is_network}}},')
    lines.append("\t}")
    lines.append("\tfor _, def := range syscalls {")
    lines.append("\t\ttable.syscalls[def.Number] = def")
    lines.append("\t\tif def.IsNetwork {")
    lines.append("\t\t\ttable.networkNumbers = append(table.networkNumbers, def.Number)")
    lines.append("\t\t}")
    lines.append("\t}")

    return "\n".join(lines) + "\n"


def generate(source: str, struct_template: str, output: str) -> None:
    syscalls = parse_header(source)
    if not syscalls:
        print(f"ERROR: no syscalls parsed from {source}", file=sys.stderr)
        sys.exit(1)

    body = build_body(syscalls)
    content = (
        FILE_HEADER.format(source=source)
        + "\n"
        + struct_template.format(body=body)
    )

    Path(output).write_text(content, encoding="utf-8")
    print(f"Generated {output}  ({len(syscalls)} syscalls from {source})")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--x86-header",
        default="/usr/include/x86_64-linux-gnu/asm/unistd_64.h",
        help="Path to x86_64 syscall header (default: %(default)s)",
    )
    parser.add_argument(
        "--arm64-header",
        default="/usr/include/asm-generic/unistd.h",
        help="Path to arm64/generic syscall header (default: %(default)s)",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).parent.parent
    out_dir = repo_root / "internal/runner/security/elfanalyzer"

    generate(
        source=args.x86_header,
        struct_template=make_struct_template(
            struct_name="X86_64SyscallTable",
            arch_desc="x86_64 Linux",
            constructor_name="NewX86_64SyscallTable",
        ),
        output=str(out_dir / "x86_syscall_numbers.go"),
    )
    generate(
        source=args.arm64_header,
        struct_template=make_struct_template(
            struct_name="ARM64LinuxSyscallTable",
            arch_desc="arm64 Linux",
            constructor_name="NewARM64LinuxSyscallTable",
            constructor_extra_comment="Syscall numbers are from the ARM64 Linux ABI (include/uapi/asm-generic/unistd.h).",
        ),
        output=str(out_dir / "arm64_syscall_numbers.go"),
    )


if __name__ == "__main__":
    main()
