// Package variable provides definitions and utilities for automatically generated variables.
//
// Auto-variables are categorized into two types based on their lifecycle:
//
//  1. Global auto-variables (generated at config load time):
//     - __runner_datetime: Timestamp when the runner process started
//     - __runner_pid: Process ID of the runner
//
//  2. Per-group auto-variables (set during group execution):
//     - __runner_workdir: Working directory for a specific group (set after workdir resolution)
//
// Global auto-variables are generated by GenerateGlobalAutoVars() and included in the
// global configuration's ExpandedVars. Per-group auto-variables are set directly
// by GroupExecutor during execution and added to the group's ExpandedVars.
package variable

import (
	"fmt"
	"os"
	"time"
)

// Clock is a function type that returns the current time.
// This allows for dependency injection of time for testing.
type Clock func() time.Time

const (
	// DatetimeLayout is the Go time format for __runner_datetime
	// Format: YYYYMMDDHHmmSS.msec (e.g., "20251005143025.123")
	DatetimeLayout = "20060102150405.000" // Go time format for YYYYMMDDHHmmSS.msec

	// AutoVarPrefix is the prefix for automatically generated internal variables (lowercase format)
	AutoVarPrefix = "__runner_"

	// AutoVarKeyDatetime is the key for the datetime auto internal variable (without prefix)
	AutoVarKeyDatetime = "datetime"
	// AutoVarKeyPID is the key for the PID auto internal variable (without prefix)
	AutoVarKeyPID = "pid"
	// AutoVarKeyWorkDir is the key for the workdir auto internal variable (without prefix)
	AutoVarKeyWorkDir = "workdir"
)

// WorkDirKey returns the auto variable key (__runner_workdir) used to store the runner
// working directory for a group during execution.
//
// Note: This variable is NOT generated by GenerateGlobalAutoVars(). It is set directly by
// GroupExecutor after resolving the group's working directory, and is only available
// at the command level (not at the group level to avoid circular references).
func WorkDirKey() string {
	return AutoVarPrefix + AutoVarKeyWorkDir
}

// DatetimeKey returns the auto variable key (__runner_datetime) for the runner datetime.
// This is a global auto-variable generated at config load time.
func DatetimeKey() string {
	return AutoVarPrefix + AutoVarKeyDatetime
}

// PIDKey returns the auto variable key (__runner_pid) for the runner PID.
// This is a global auto-variable generated at config load time.
func PIDKey() string {
	return AutoVarPrefix + AutoVarKeyPID
}

// GenerateGlobalAutoVars generates global automatic variables (__runner_datetime and __runner_pid)
// and returns them as a map. This should be called once at configuration load time.
//
// Note: This function does NOT generate __runner_workdir, which is a per-group variable
// set by GroupExecutor during execution after the working directory is resolved.
//
// The clock parameter allows for time injection for testing; pass time.Now for production use.
func GenerateGlobalAutoVars(clock Clock) map[string]string {
	if clock == nil {
		clock = time.Now
	}

	autoVars := make(map[string]string)

	// Generate __runner_datetime in UTC with format YYYYMMDDHHmmSS.msec
	now := clock().UTC()
	autoVars[DatetimeKey()] = now.Format(DatetimeLayout)

	// Generate __runner_pid
	autoVars[PIDKey()] = fmt.Sprintf("%d", os.Getpid())

	return autoVars
}
